---
title: "#NGSSchat sentiment: descriptive statistics"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
params:
  d: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, cache = FALSE)
```

```{r, renaming-params}
d <- params$d
```

# Descriptive analysis

## Variables used in the analysis

```{r, desciptive-stats}
d %>% 
  select(type_of_tweet, year_fct, scale_neg, scale_pos, senti_scale, senti_binary, state_master, screen_name, year_of_post, near_adoption, before_adoption, after_adoption, no_adoption, favorite_count_user, retweet_count_user, followers_count, friends_count, time_on_twitter_period, reply_count, favorite_count, retweet_count, statuses_count, isTeacher) %>% 
  skimr::skim()
```

## Time series

```{r, ts-plot}
d %>% 
  mutate(date_r = lubridate::round_date(created_at, "day")) %>% 
  count(date_r) %>% 
  ggplot(aes(y = n, x = date_r)) +
  geom_line(color = 'lightgray') +
  geom_point(color = 'black') +
  hrbrthemes::theme_ipsum() +
  xlab(NULL) +
  ylab("Posts") +
  ggtitle("Posts to the #NGSSchat Hashtag on Twitter Per Day")

ggsave("img/ngsschat-posts-per-day.png", width = 8, height = 6)
```

## overall

```{r}
d %>% count(senti_binary) %>% 
  spread(senti_binary, n) %>% 
  set_names(c("neg", "pos")) %>% 
  mutate(senti_ratio = neg/pos)
```

## by year 

```{r}
d %>% count(year_of_post, senti_binary) %>% 
  spread(senti_binary, n) %>% 
  set_names(c("year_of_post", "neg", "pos")) %>%
  mutate(senti_ratio = neg/pos) %>% 
  ggplot(aes(x = year_of_post, y = senti_ratio)) +
  geom_point() +
  geom_line() +
  geom_smooth()
```

## by tweet type

```{r}
d %>% 
  count(type_of_tweet, senti_binary) %>% 
  spread(senti_binary, n) %>% 
  set_names(c("type_of_tweet", "neg", "pos")) %>% 
  mutate(senti_ratio = neg/pos)
```

## by state

```{r}
d %>% 
  count(state_master, senti_binary) %>% 
  spread(senti_binary, n) %>% 
  set_names(c("state_master", "neg", "pos")) %>% 
  mutate(senti_ratio = neg/pos) %>% 
  arrange(desc(senti_ratio)) %>% 
  ggplot(aes(x = reorder(state_master, senti_ratio), y = senti_ratio)) +
  geom_col() +
  coord_flip()
```

## by state, by year

```{r}
d %>% 
  filter(year_of_post >= 2012) %>% 
  count(state_master, year_of_post, senti_binary) %>% 
  spread(senti_binary, n) %>% 
  set_names(c("state_master", "year_of_post", "neg", "pos")) %>% 
  mutate(senti_ratio = neg/pos) %>% 
  arrange(desc(senti_ratio)) %>% 
  ggplot(aes(x = reorder(state_master, senti_ratio), y = senti_ratio)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~year_of_post)
```

## by adoption status

```{r}
d %>% 
  count(adoption_key, senti_binary) %>% 
  spread(senti_binary, n) %>% 
  set_names(c("adoption_status", "neg", "pos")) %>% 
  mutate(senti_ratio = neg/pos) %>% 
  arrange(desc(senti_ratio))
```

## by adoption status by year

```{r}
d %>% 
  filter(year_of_post >= 2012) %>% 
  count(adoption_key, year_of_post, senti_binary) %>% 
  spread(senti_binary, n) %>% 
  set_names(c("state_master", "year_of_post", "neg", "pos")) %>% 
  mutate(senti_ratio = neg/pos) %>% 
  arrange(desc(senti_ratio)) %>% 
  ggplot(aes(x = reorder(state_master, senti_ratio), y = senti_ratio)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~year_of_post)
```
