---
title: "Final models"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
params:
  d: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, cache = FALSE)
knitr::clean_cache()
```

```{r, renaming-params}
d <- params$d
d <- readd(data_to_model)
```

# Original DV, senti_scale composite variable

```{r, m_final, eval = TRUE}
m_senti_scale <- lmer(senti_scale ~ 1 + 
                        
                        type_of_tweet + 
                        
                        isTeacher + 
                        
                        year_of_post_centered + 
                        
                        favorite_count + retweet_count + reply_count +
                        favorite_count_user +
                        retweet_count_user +
                        statuses_count +
                        followers_count +
                        friends_count +
                        
                        postedNGSSchat + postedChatSession + hasJoinedChat + scale(total_n_chats) +
                        (1|screen_name), data = d)

write_rds(m_final, "out/m_final.rds")

sjPlot::tab_model(m_senti_scale, show.icc = TRUE, show.ci = FALSE, show.se = TRUE, show.std = "std")
performance::icc(m_senti_scale, by_group = TRUE)
equatiomatic::extract_eq(m_senti_scale, wrap = TRUE)
```

## scaled variable
```{r, m-senti-scale, eval = TRUE}
m_senti_scale <- lmer(senti_scale ~ 1 + 
                        
                        type_of_tweet + # NGSSchat - chat, #NGSSChat non-chat, non-#NGSSchat (inclues e.g. NGSS)
                        
                        isTeacher + # participant is a teacher or not
                        
                        year_of_post_centered + 
                        
                        favorite_count + retweet_count + reply_count + # these are tweet-level variables; may not need to include
                        
                        postedNGSSchat + postedChatSession + hasJoinedChat + scale(total_n_chats) + # these are user-level variables; see describe-data.Rmd for definitions
                        
                        (1|screen_name), 
                      
                      data = d)

write_rds(m_final, "out/m_senti_scale.rds")

sjPlot::tab_model(m_senti_scale, show.icc = TRUE, show.ci = FALSE, show.se = TRUE, show.std = "std")
performance::icc(m_senti_scale, by_group = TRUE)
equatiomatic::extract_eq(m_senti_scale, wrap = TRUE)
```

## just positive

```{r, m-senti-scale-pos, eval = TRUE}
m_senti_scale_pos <- lmer(senti_scale ~ 1 + 
                        
                        type_of_tweet + # NGSSchat - chat, #NGSSChat non-chat, non-#NGSSchat (inclues e.g. NGSS)
                        
                        isTeacher + # participant is a teacher or not
                        
                        year_of_post_centered + 
                        
                        favorite_count + retweet_count + reply_count + # these are tweet-level variables; may not need to include
                        
                        postedNGSSchat + postedChatSession + hasJoinedChat + scale(total_n_chats) + # these are user-level variables; see describe-data.Rmd for definitions
                        
                        (1|screen_name), 
                      
                      data = d)

write_rds(m_senti_scale_pos, "out/m_senti_scale.rds")

sjPlot::tab_model(m_senti_scale_pos, show.icc = TRUE, show.ci = FALSE, show.se = TRUE, show.std = "std")
performance::icc(m_senti_scale_pos, by_group = TRUE)
equatiomatic::extract_eq(m_senti_scale_pos, wrap = TRUE)
```

## just negative

```{r, m-senti-scale-neg, eval = TRUE}
m_senti_scale_neg <- lmer(scale_neg ~ 1 + 
                            
                            type_of_tweet + # NGSSchat - chat, #NGSSChat non-chat, non-#NGSSchat (inclues e.g. NGSS)
                            
                            isTeacher + # participant is a teacher or not
                            
                            year_of_post_centered + 
                            
                            favorite_count + retweet_count + reply_count + # these are tweet-level variables; may not need to include
                            
                            postedNGSSchat + postedChatSession + hasJoinedChat + scale(total_n_chats) + # these are user-level variables; see describe-data.Rmd for definitions
                            
                            (1|screen_name), 
                          
                          data = d)

write_rds(m_senti_scale_neg, "out/m-senti-scale-neg.rds")

sjPlot::tab_model(m_senti_scale_neg, show.icc = TRUE, show.ci = FALSE, show.se = TRUE, show.std = "std")
performance::icc(m_senti_scale_neg, by_group = TRUE)
equatiomatic::extract_eq(m_senti_scale_neg, wrap = TRUE)
```

# LIWC affect

## scaled variable

```{r, m-liwc, eval = TRUE}
m_liwc <- lmer(liwc_affect_scale ~ 
                 
                 type_of_tweet + # NGSSchat - chat, #NGSSChat non-chat, non-#NGSSchat (inclues e.g. NGSS)
                 
                 isTeacher + # participant is a teacher or not
                 
                 year_of_post_centered + 
                 
                 favorite_count + retweet_count + reply_count + # these are tweet-level variables; may not need to include
                 
                 postedNGSSchat + postedChatSession + hasJoinedChat + scale(total_n_chats) + # these are user-level variables; see describe-data.Rmd for definitions
                 
                 (1|screen_name), 
               
               data = d)

write_rds(m_liwc, "out/m-liwc.rds")

sjPlot::tab_model(m_liwc, show.icc = TRUE, show.ci = FALSE, show.se = TRUE, show.std = "std")
performance::icc(m_liwc, by_group = TRUE)
equatiomatic::extract_eq(m_liwc, wrap = TRUE)
````

## just positive

```{r, m_final_posemo, eval = TRUE}
m_liwc_pos <- lmer(posemo ~ 
                     
                     type_of_tweet + # NGSSchat - chat, #NGSSChat non-chat, non-#NGSSchat (inclues e.g. NGSS)
                     
                     isTeacher + # participant is a teacher or not
                     
                     year_of_post_centered + 
                     
                     favorite_count + retweet_count + reply_count + # these are tweet-level variables; may not need to include
                     
                     postedNGSSchat + postedChatSession + hasJoinedChat + scale(total_n_chats) + # these are user-level variables; see describe-data.Rmd for definitions
                     
                     (1|screen_name), 
                   
                   data = d)

write_rds(m_liwc_pos, "out/m-liwc-pos.rds")

sjPlot::tab_model(m_liwc_pos, show.icc = TRUE, show.ci = FALSE, show.se = TRUE, show.std = "std")
performance::icc(m_liwc_pos, by_group = TRUE)
equatiomatic::extract_eq(m_liwc_pos, wrap = TRUE)
````

## just negative

```{r, m-liwc-neg, eval = TRUE}
m_liwc_neg <- lmer(negemo ~ 
                     
                     type_of_tweet + # NGSSchat - chat, #NGSSChat non-chat, non-#NGSSchat (inclues e.g. NGSS)
                     
                     isTeacher + # participant is a teacher or not
                     
                     year_of_post_centered + 
                     
                     favorite_count + retweet_count + reply_count + # these are tweet-level variables; may not need to include
                     
                     postedNGSSchat + postedChatSession + hasJoinedChat + scale(total_n_chats) + # these are user-level variables; see describe-data.Rmd for definitions
                     
                     (1|screen_name), 
                   
                   data = d)

write_rds(m_liwc_neg, "out/m-liwc-neg.rds")

sjPlot::tab_model(m_liwc_neg, show.icc = TRUE, show.ci = FALSE, show.se = TRUE, show.std = "std")
performance::icc(m_liwc_neg, by_group = TRUE)
equatiomatic::extract_eq(m_liwc_neg, wrap = TRUE)
````
