---
title: "Generality classifier leave one out cross-validation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(quanteda)
library(quanteda.textmodels)
library(quanteda.classifiers)

d <- read_csv("coded-profiles.csv")
d <- d %>% 
    slice(1:517)

d <- d %>% 
    mutate(cat_code = recode(Code,
                             `1` = "Teacher",
                             `2` = "Other",
                             `3` = "Other",
                             `4` = "Other",
                             `5` = "Other",
                             `8` = "Other",
                             `9` = "Other",
                             `10` = "Other",
                             `6` = "Other",
                             `7` = "Other",
                             `11` = "Other"))

# d <- d %>% 
#     mutate(cat_code = recode(Code,
#                              `1` = "Teacher",
#                              `2` = "Administrator",
#                              `3` = "Administrator",
#                              `4` = "Researcher",
#                              `5` = "Other",
#                              `8` = "Other",
#                              `9` = "Other",
#                              `10` = "Other",
#                              `6` = "Organization",
#                              `7` = "Organization",
#                              `11` = "Other"))

resample <- function(gd, code, row, classifier = "nb", verbose = F) {
    
    gd <- gd %>%
        select(text = description, everything())
    
    gds <- gd[row, ]
    gd <- gd[-row, ]
    
    tok <- tokens(gd$text, remove_punct = TRUE, remove_symbols = TRUE, remove_url = TRUE, remove_numbers = TRUE)
    
    dfm_training <- dfm(tok, stem = TRUE)
    dfm_training <- dfm_training %>% as.matrix() %>% as.data.frame()
    dfm_training$n <- gd$n
    dfm_training$statusesCount <- gd$statusesCount
    dfm_training$friendsCount <- gd$friendsCount
    dfm_training$followersCount <- gd$followersCount
    dfm_training$favoritesCount <- gd$favoritesCount
    dfm_training$years_on_twitter <- 2020 - lubridate::year(gd$created)
    dfm_training$listCount <- gd$listCount
    dfm_training <- dfm_training %>% as.dfm()
    
    if (classifier == "svm") {
        m1 <- quanteda.textmodels::textmodel_svm(dfm_training, docvars(dfm(corpus(gd)), code))
    } else if (classifier == "nn") {
        m1 <- quanteda.classifiers::textmodel_mlp(dfm_training, docvars(dfm(corpus(gd)), code), verbose = verbose)
    } else if (classifier == "nb") {
        m1 <- textmodel_nb(dfm_training, docvars(dfm(corpus(gd)), code))
    } else if (classifier == "nn_con") {
        m1 <- quanteda.classifiers::textmodel_cnnlstmemb(dfm_training, docvars(dfm(corpus(gd)), code))
    }
    
     tok1 <- tokens(gds$text, remove_punct = TRUE, remove_symbols = TRUE, remove_url = TRUE, remove_numbers = TRUE)
    
    dfm_test <- dfm(tok1, stem = TRUE)
    
    dfm_test <- dfm_test %>% as.matrix() %>% as.data.frame()
    dfm_test$n <- gds$n
    dfm_test$statusesCount <- gds$statusesCount
    dfm_test$friendsCount <- gds$friendsCount
    dfm_test$followersCount <- gds$followersCount
    dfm_test$favoritesCount <- gds$favoritesCount
    dfm_test$years_on_twitter <- 2020 - lubridate::year(gds$created)
    dfm_test$listCount <- gds$listCount
    dfm_test <- dfm_test %>% as.dfm()
    
    dfmat_matched <- dfm_match(dfm_test, features = featnames(dfm_training))
    
    actual_class <- docvars(dfm(corpus(gds)), code)
    
    predicted_class <- predict(m1, newdata = dfmat_matched)
    
    if (verbose == verbose) {
        print(str_c("### Completed bootstrap sample: ", row, " ###"))
    }
    data.frame(actual_class = actual_class, predicted_class = predicted_class)
}

get_performance <- function(do) {
    # https://www.dataschool.io/simple-guide-to-confusion-matrix-terminology/
    tab_class <- table(do$actual_class, do$predicted_class)
    c <- caret::confusionMatrix(tab_class, mode = "everything")
    return(c)
}

run_model <- function(gd, code, .f = resample, classifier, by) {
    do <- map_df(.x = seq(from = 1, to = nrow(gd), by = by),
                 gd = gd,
                 code = code,
                 .f = .f,
                 classifier = classifier)
    do
    get_performance(do)
}
```

```{r}
onb <- run_model(gd = d, code = "cat_code", classifier = "nb", by = 1)
nsvm <- run_model(gd = d, code = "cat_code", classifier = "svm", by = 1)
nn1 <- run_model(gd = d, code = "cat_code", classifier = "nn", by = 1)
# nn2 <- run_model(gd = d, code = "cat_code", classifier = "nn_con")
```