---
title: "#NGSSchat sentiment modeling"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

## loading, setting up

```{r, load-packages}
library(tidyverse)
library(lme4)
library(sjPlot)
```

```{r, read-and-prep-data}
d <- read_csv("NGSSchat_sentiment_states_newly_revised.csv")

d$year <- lubridate::year(d$created_at)

d$state <- d$state %>% 
  str_remove(":main") %>%
  str_remove(":south") %>%
  str_remove(":north") %>%
  str_remove(":long island") %>%
  str_remove(":manhattan") %>%
  str_remove(":whidbey island") %>%
  str_remove(":martha's vineyard")
```

```{r, proc-state-data}
state_data <- read_csv("ngsschat-state-data.csv")

state_data <- state_data %>% 
  select(State, Early:Not) %>% 
  gather(key, val, -State) %>% 
  rename(state = State,
         adoption_status = key) %>% 
  mutate(state = tolower(state),
         adoption_status = if_else(adoption_status == "Near", "Mid", adoption_status),
         adoption_status = factor(adoption_status, levels = c("Not", "Early", "Mid", "Late"))) %>% 
  filter(!is.na(val)) %>% 
  select(-val)
```

```{r, joining-state-data}
d <- d %>% 
  left_join(state_data)
```

```{r, scaling-year}
d$year <- as.numeric(scale(d$year))
```

## descriptive stats

```{r, desciptive-stats}
d %>% 
  select(posRate, negRate, state, screen_name, year, adoption_status) %>% 
  skimr::skim()
```

# Models

## Just modeling the effect of state

```{r, m0-state}
m0_pos_state <- lmer(posRate ~ 1 + (1|state), data = d)
m0_neg_state <- lmer(posRate ~ 1 + (1|state), data = d)


sjPlot::tab_model(m0_pos_state)
sjPlot::tab_model(m0_neg_state)

performance::icc(m0_pos_state, by_group = TRUE)
performance::icc(m0_neg_state, by_group = TRUE)
```

## Just modeling the effect of screen_name

```{r, m0-screen_name}
m0_pos_screen_name <- lmer(posRate ~ 1 + (1|screen_name), data = d)
m0_neg_screen_name <- lmer(posRate ~ 1 + (1|screen_name), data = d)


sjPlot::tab_model(m0_pos_screen_name)
sjPlot::tab_model(m0_neg_screen_name)

performance::icc(m0_pos_screen_name, by_group = TRUE)
performance::icc(m0_neg_screen_name, by_group = TRUE)
```

## Both state and screen name 

```{r, m1}
m1_pos <- lmer(posRate ~ 1 + (1|state) + (1|screen_name), data = d)
m1_neg <- lmer(posRate ~ 1 + (1|state) + (1|screen_name), data = d)


sjPlot::tab_model(m1_pos, show.icc = TRUE)
sjPlot::tab_model(m1_neg, show.icc = TRUE)

performance::icc(m1_pos, by_group = TRUE)
performance::icc(m1_neg, by_group = TRUE)
```

## Adding year

```{r, m2}
m2_pos <- lmer(posRate ~ 1 + year + (1|state) + (1|screen_name), data = d)
m2_neg <- lmer(posRate ~ 1 + year + (1|state) + (1|screen_name), data = d)

sjPlot::tab_model(m2_pos, show.icc = TRUE)
sjPlot::tab_model(m2_neg, show.icc = TRUE)

performance::icc(m2_pos, by_group = TRUE)
performance::icc(m2_neg, by_group = TRUE)
```

## Adding adoption status

```{r, m3-lmer}
m3_pos <- lmer(posRate ~ 1 + year + adoption_status + (1|state) + (1|screen_name), data = d)
m3_neg <- lmer(posRate ~ 1 + year + adoption_status + (1|state) + (1|screen_name), data = d)

sjPlot::tab_model(m3_pos, show.icc = TRUE)
sjPlot::tab_model(m3_neg, show.icc = TRUE)

performance::icc(m3_pos, by_group = TRUE)
performance::icc(m3_neg, by_group = TRUE)
```

## Random slope for year across state

```{r, m4-lmer}
m4_pos <- lmer(posRate ~ 1 + year + adoption_status + (year|state) + (1|screen_name), data = d)
m4_neg <- lmer(posRate ~ 1 + year + adoption_status + (year|state) + (1|screen_name), data = d)

sjPlot::tab_model(m4_pos, show.icc = TRUE)
sjPlot::tab_model(m4_neg, show.icc = TRUE)

performance::icc(m4_pos, by_group = TRUE)
performance::icc(m4_neg, by_group = TRUE)
```

## Random slope for adoption_status across state

```{r, m5-lmer}
m5_pos <- lmer(posRate ~ 1 + year + adoption_status + (year + adoption_status|state) + (1|screen_name), data = d)
m5_neg <- lmer(posRate ~ 1 + year + adoption_status + (year + adoption_status|state) + (1|screen_name), data = d)

sjPlot::tab_model(m5_pos, show.icc = TRUE)
sjPlot::tab_model(m5_neg, show.icc = TRUE)

performance::icc(m5_pos, by_group = TRUE)
performance::icc(m5_neg, by_group = TRUE)
```

Inspecting random effects levels for states

```{r}
p <- sjPlot::plot_model(m3_pos, type = "re", sort.est = TRUE)
p[[2]]
```

## Next models

- adding chat versus non-chat