---
title: "Models"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
params:
  null_model: ""
  full_model: ""
  augmented_full_model_data: ""
  state_ranefs: ""
  full_model_with_three_way_interact: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set()
```

```{r}
icc(null_model, by_group = TRUE)

tab_model(full_model, show.icc = TRUE)
```

```{r eval = FALSE}
equatiomatic::extract_eq(full_model)
```

```{r}
tab_model(full_model_with_three_way_interact, show.icc = TRUE)
```

```{r}
mod_d <- full_model@frame
```

```{r}
pred_frame_chat <- data.frame(type_of_tweet = rep(c("non-ngsschat", 
                                               "ngsschat-chat", 
                                               "ngsschat-non-chat"), each = 2*11),
                         time_on_twitter_s = mean(mod_d$time_on_twitter_s, na.rm = TRUE),
                         is_teacher = 0,
                         year_of_post_centered = seq(-5, 5, 1),
                         has_joined_chat = 0,
                         n_posted_chatsessions_s = mean(mod_d$n_posted_chatsessions_s, na.rm = T),
                         n_posted_ngsschat_nonchat_s = mean(mod_d$n_posted_ngsschat_nonchat_s, na.rm = T),
                         n_posted_non_ngsschat_s = mean(mod_d$n_posted_non_ngsschat_s, na.rm = T),
                         adopted_fct = factor("not-adopted",
                                              levels = c("not-adopted", "adopted", "missing")),
                         user_id = -999
)
pred_frame_tch <- data.frame(type_of_tweet = "non-ngsschat",
                         time_on_twitter_s = mean(mod_d$time_on_twitter_s, na.rm = TRUE),
                         is_teacher = rep(c(0, 1), 3*11),
                         year_of_post_centered = seq(-5, 5, 1),
                         has_joined_chat = 0,
                         n_posted_chatsessions_s = mean(mod_d$n_posted_chatsessions_s, na.rm = T),
                         n_posted_ngsschat_nonchat_s = mean(mod_d$n_posted_ngsschat_nonchat_s, na.rm = T),
                         n_posted_non_ngsschat_s = mean(mod_d$n_posted_non_ngsschat_s, na.rm = T),
                         adopted_fct = factor("not-adopted",
                                              levels = c("not-adopted", "adopted", "missing")),
                         user_id = -999
)
```

```{r}
pred_frame_chat$prediction <- predict(full_model, 
                                      newdata = pred_frame_chat, 
                                      allow.new.levels = TRUE)
pred_frame_tch$prediction <- predict(full_model, 
                                      newdata = pred_frame_tch, 
                                      allow.new.levels = TRUE)

chat_preds_y <- pred_frame_chat %>% 
  filter(is_teacher == 0) %>% 
  group_by(type_of_tweet) %>% 
  summarize(prediction = max(prediction))

tch_preds_y <- pred_frame_tch %>% 
  filter(type_of_tweet == "non-ngsschat") %>% 
  group_by(is_teacher) %>% 
  summarize(prediction = max(prediction))
  
type_order <- match(
  c("non-ngsschat", "ngsschat-chat", "ngsschat-non-chat"), 
  chat_preds_y$type_of_tweet
)

tch_order <- match(
  c(0, 1), 
  tch_preds_y$is_teacher
)

chat_label_frame <- data.frame(year_of_post_centered = 5,
                          prediction = chat_preds_y$prediction[type_order],
                          type_of_tweet = c("non-ngsschat", 
                                            "ngsschat-chat", 
                                            "ngsschat-non-chat"),
                          label = c("Non-#NGSSchat",
                                    "#NGSSChat",
                                    "#NGSSChat non-chat"))

tch_label_frame <- data.frame(year_of_post_centered = 5,
                              prediction = tch_preds_y$prediction[tch_order],
                              is_teacher = c(0, 1),
                              label = c("Non-Teachers",
                                        "Teachers"))
```

```{r}
extrafont::loadfonts()

theme_set(theme_minimal(15))

p1 <- pred_frame_tch %>% 
  filter(type_of_tweet == "non-ngsschat") %>% 
  mutate(is_teacher = ifelse(is_teacher == 0, "Non-Teachers", "Teachers")) %>% 
  ggplot(aes(year_of_post_centered + 2016, prediction)) +
  annotate("rect", xmin = 2021, xmax = Inf, ymin = -Inf, ymax = Inf,
           color = "#ffffff", fill = "#ffffff") +
  geom_line(aes(color = is_teacher), 
            size = 1.3) +
  geom_text(aes(label = label),
            color = "#373B41",
            family = "Times New Roman",
            hjust = 0,
            nudge_x = 0.2,
            data = tch_label_frame) +
  scale_color_manual(values = c("#A992B2", "#A87645")) + 
  guides(color = "none") +
  scale_x_continuous("", 
                     breaks = seq(2010, 2030, 2),
                     labels = rep("", 11),
                     expand = expansion(add = c(0, 3.3))) +
  scale_y_continuous("",
                     breaks = seq(0, 1, .2),
                     labels = format(seq(0, 1, .2), nsmall = 1),
                     expand = expansion(add = c(0.03, 0.1))) +
  labs(title = "A") +
  theme(text = element_text(family = "Times New Roman"))

p2 <- pred_frame_chat %>% 
  ggplot(aes(year_of_post_centered + 2016, prediction)) +
  annotate("rect", xmin = 2021, xmax = Inf, ymin = -Inf, ymax = Inf,
           color = "#ffffff", fill = "#ffffff") +
  geom_line(aes(color = type_of_tweet), 
            size = 1.3) +
  geom_text(aes(label = label),
            color = "#373B41",
            family = "Times New Roman",
            hjust = 0,
            nudge_x = 0.2,
            data = chat_label_frame) +
  scale_color_manual(values = c("#373B41", "#67E0CF", "#ABCFED")) +
  guides(color = "none",
         fill = "none") +
  scale_x_continuous("", 
                     breaks = seq(2010, 2030, 2),
                     labels = c(seq(2010, 2020, 2), rep("", 5)),
                     expand = expansion(add = c(0, 3.3))) +
  scale_y_continuous("",
                     breaks = seq(0, 1, 0.2),
                     labels = format(seq(0, 1, .2), nsmall = 1),
                     expand = expansion(0, 0.18)) +
  labs(title = "B") +
  theme(text = element_text(family = "Times New Roman"))


library(ggpubr)
combined <- ggarrange(p1, p2, ncol = 1)

annotate_figure(
  combined,
  left = text_grob("Scaled Model-Predicted Sentiment Score", 
                   rot = 90,
                   family = "Times New Roman")
  )

ggsave("interactions.png", width = 6.5, height = 8, dpi = 800)
```

```{r}
samp_d <- mod_d %>% 
  select(year_of_post_centered, 
         is_teacher, 
         type_of_tweet, 
         senti_scale_s) %>% 
  mutate(is_teacher = ifelse(is_teacher == 0, "Non-Teachers", "Teachers")) %>% 
  group_by(year_of_post_centered, is_teacher, type_of_tweet) %>% 
  slice_sample(prop = 0.1) 

# pred_frame %>% 
#   mutate(is_teacher = ifelse(is_teacher == 0, "Non-Teachers", "Teachers")) %>% 
#   ggplot(aes(year_of_post_centered + 2016, prediction)) +
#   geom_point(aes(year_of_post_centered + 2016, senti_scale_s),
#              samp_d,
#              color = "gray80") +
#   geom_line(size = 1.3) +
#   facet_grid(is_teacher ~ type_of_tweet)
```