---
title: "preparing-data-for-modeling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, load-packages}
library(maps)
library(tidyverse)
```

```{r, read-and-prep-data}
load('data_final_2020_09_02.rda')
```

```{r, loading-data}
tweets_dl <- tweets_dl %>% as_tibble()

d <- tweets_dl
rm(tweets_dl)
```

```{r, ts-plot}
d %>% 
  mutate(date_r = lubridate::round_date(created_at, "day")) %>% 
  count(date_r) %>% 
  ggplot(aes(y = n, x = date_r)) +
  geom_line(color = 'lightgray') +
  geom_point(color = 'black') +
  hrbrthemes::theme_ipsum() +
  xlab(NULL) +
  ylab("Posts") +
  ggtitle("Posts to the #NGSSchat Hashtag on Twitter Per Day")

ggsave("img/ngsschat-posts-per-day.png", width = 8, height = 6)
```

```{r, proc-state-data}
state_data <- read_csv("data-raw/ngsschat-state-data.csv")

state_acronyms <- read_csv("data-raw/state-acronyms.csv") %>% 
  select(state, acronym) %>% 
  mutate(state = tolower(state))

state_data$month <- state_data$date_month %>% 
  str_split("\\-") %>% 
  purrr::map(~.[[1]]) %>% as.integer()

state_data$year_month <- as.numeric(str_c(state_data$date_year, ".", state_data$month))

state_data_merge <- state_data %>% 
  rename(state = State) %>% 
  mutate(state = tolower(state)) %>% 
  select(state, year_month, adopted = Not, year = date_year, modified, lead) %>% 
  mutate(adopted = if_else(is.na(adopted), 1, 0)) %>% 
  mutate(year_adopted = year) %>% 
  mutate(modified = ifelse(is.na(modified), 0, modified)) %>% 
  mutate(lead = ifelse(lead == "Yes", 1, lead),
         lead = ifelse(is.na(lead), 0, lead))

state_data_adopt <- state_data %>%
  select(State, Early:Not) %>%
  gather(key, val, -State) %>%
  rename(state = State,
         adoption_status = key) %>%
  mutate(state = tolower(state),
         adoption_status = if_else(adoption_status == "Near", "Mid", adoption_status),
         adoption_status = factor(adoption_status, levels = c("Not", "Early", "Mid", "Late"))) %>%
  filter(!is.na(val)) %>%
  select(-val) %>% 
  select(state, adoption_status)

state_data_merged <- state_data_merge %>% 
  left_join(state_data_adopt) %>% 
  left_join(state_acronyms)

state_data_final <- state_data_merged %>% 
  complete(state, year = 2011:2020) %>% 
  group_by(state) %>% 
  fill(adopted, year_month, adoption_status, acronym) %>% 
  fill(adopted, year_month, adoption_status, acronym, .direction = "up")

state_data_final <- state_data_final %>% 
  mutate(year_adopted_plus = year_adopted + 1) %>% 
  mutate(year_adopted_minus = year_adopted - 1) %>% 
  fill(year_adopted, year_adopted_minus, year_adopted_plus, .direction = "updown") %>% 
  mutate(near_adoption = ifelse(year == year_adopted, 1, 0),
         near_adoption = ifelse(year == year_adopted_minus, 1, near_adoption),
         near_adoption = ifelse(year == year_adopted_plus, 1, near_adoption)) %>% 
  mutate(before_adoption = ifelse(year < year_adopted_minus, 1, 0)) %>% 
  mutate(after_adoption = ifelse(year > year_adopted_plus, 1, 0)) %>% 
  fill(modified, lead, .direction = 'updown') %>% 
  ungroup()

state_data_final <- state_data_final %>% 
  mutate(no_adoption = ifelse(adoption_status == "Not", 1, 0)) %>% 
  select(state, year, contains("_adoption"), modified, lead)

dstatus <- state_data_final %>% 
  select(contains("_adoption")) %>% 
  gather(key, val) %>% 
  mutate(val = ifelse(is.na(val), 0, val)) %>% 
  filter(val == 1) %>% 
  select(-val) %>% 
  rename(adoption_key = key)

state_data_final$adoption_key <- factor(dstatus$adoption_key) %>% 
  forcats::fct_relevel("no_adoption")

state_data_final <- rename(state_data_final, state_master = state)
```

```{r, joining-state-data}
d <- d %>% 
  left_join(state_data_final)
```

```{r, creating-year-factor}
d$year_fct <- factor(d$year) %>% forcats::fct_relevel('2016')
```

```{r, add-tweet-type}
d %>% 
  count(isChat)

d <- d %>% 
  mutate(type_of_tweet = ifelse(isChat == 0, "ngsschat-non-chat",
                                ifelse(isChat == 1, "ngsschat-chat", NA))) %>% 
  mutate(type_of_tweet = ifelse(is.na(type_of_tweet), "non-ngsschat", type_of_tweet))
```

including english only 

```{r, filtering-en}
d <- d %>% filter(lang == "en")
```


```{r}
d <- d %>% 
  mutate(year_centered = scale(year, scale = FALSE),
         time_on_twitter = (d$created_at - d$account_created_at) / (60 * 60 * 24) / 365,
         year_fct = factor(as.numeric(as.character(d$year_fct))))
```

## descriptive stats

New vars include:

favorite_count_user, followers_count, friends_count, time_on_twitter_period, reply_count, favorite_count, retweet_count, statuses_count

```{r, desciptive-stats}
d %>% 
  select(type_of_tweet, year_centered, year_fct, scale_neg, scale_pos, senti_scale, senti_binary, state_master, screen_name, year, near_adoption, before_adoption, after_adoption, no_adoption, favorite_count_user, retweet_count_user, followers_count, friends_count, time_on_twitter_period, reply_count, favorite_count, retweet_count, statuses_count) %>% 
  skimr::skim()
```


```{r}
write_rds(rtweet::flatten(d), 'data/ngsschat-data-for-modeling.rds')
```
